### ISSUE TITLE
Improve Rzk Playground code (address minor issues)

### ISSUE THREAD

**Issue by fizruk** [rzk-lang/rzk#122]
- [x] Support `snippet_url` param (it was dropped in #84)
- [x] Improve the code for the playground:
  - [x] Address comment https://github.com/rzk-lang/rzk/pull/118#discussion_r1342177094
  - [x] Address comment https://github.com/rzk-lang/rzk/pull/118#discussion_r1342179003

**Comment by aabounegm** [comment]
Is there anything else left to do for this issue or should it have been closed by #124?
