### ISSUE TITLE
Syntax sugar for nested Sigma types

### ISSUE THREAD

**Issue by fizruk** [rzk-lang/rzk#140]
It is possible to generalise `Σ` to accept arbitrary parameters like in `#define`:

```agda
Σ (a : A), ∑ (b : B), C a b       -- current syntax (right assoc)
Σ ((a, b) : ∑ (a : A), B), C a b  -- current syntax (left assoc)
Σ (a : A) (b : B), C a b          -- generalised syntax (should be desugared to left assoc)
```

_Originally posted by @fizruk in https://github.com/emilyriehl/yoneda/issues/14#issuecomment-1621238821_

Correspondingly, there should be syntax sugar for pair patterns:

```agda
\ (a, (b, c)) -> ...        -- explicit patterns (right assoc)
\ ((a, b), c) -> ...        -- explicit patterns (left assoc)
\ (a, b, c) -> ...          -- explicit patterns (should be desugared to left assoc)
```

This should be a simple change.

**Comment by TashiWalde** [comment]
Ideally it should be possible to fully specify the mixed associativity of a `Σ`-type with only a single `Σ` symbol.
For example I would like to be able to write any of the following if I care about the exact bracketting of my terms.
```
Σ (a : A , (b : B a , c : C a b)) , (d : D a b c)
Σ (a : A , b : B a) , (c : C a b , d : D a b c)
```

**Comment by TashiWalde** [comment]
And I would probably prefer one of the following for the unbiased version (which then secretly desugars to left assoc.
```
Σ (a : A , b : B a , C a b)
Σ (a : A) (b : B a) (C a b)
```
It just seems a bit asymmetric to have one but not all commas.

**Comment by TashiWalde** [comment]
One additional alternative which I also quite like is to use the `×` as an infix operator for dependent sums. For example:
```
(a : A) × B × (c : C a) × (D a c) 
```
